export const mockChats = [
    {
        id: "1",
        name: "CyberAgent_Neo",
        lastMessage: "The matrix has been updated...",
        timestamp: "2m",
        unreadCount: 3,
        isOnline: true,
        isGroup: false,
    },
    {
        id: "2",
        name: "Neural Collective",
        lastMessage: "Trinity: We need to discuss the protocol",
        timestamp: "15m",
        unreadCount: 7,
        isOnline: false,
        isGroup: true,
        participants: 8,
    },
    {
        id: "3",
        name: "Ghost_Shell",
        lastMessage: "Data stream is corrupted",
        timestamp: "1h",
        unreadCount: 0,
        isOnline: true,
        isGroup: false,
    },
    {
        id: "4",
        name: "Quantum Hackers",
        lastMessage: "Morpheus: The code is ready",
        timestamp: "2h",
        unreadCount: 12,
        isOnline: true,
        isGroup: true,
        participants: 15,
    },
    {
        id: "5",
        name: "Digital_Phantom",
        lastMessage: "See you in the grid tonight",
        timestamp: "1d",
        unreadCount: 0,
        isOnline: false,
        isGroup: false,
    },
];
